### ISSUE TITLE
"chatter" privilege not assignable

### ISSUE THREAD

**Issue by Bladestar2105** [appgurueu/adv_chat#4]
Hello guys,

first of all this is a very nice mod :-)
But I have a problem. I cannot assign the "chatter" privilege.
If I try I get this message: unknown privilege chatter
Modlib and chatlib are installed and chatting ingame and with discord bridge works very good.
How can I fix this?

**Comment by appgurueu** [comment]
> Hello guys,
> 
> first of all this is a very nice mod :-) But I have a problem. I cannot assign the "chatter" privilege. If I try I get this message: unknown privilege chatter Modlib and chatlib are installed and chatting ingame and with discord bridge works very good. How can I fix this?

Sorry for the late reply. The `chatter` priv isn't an actual priv IIRC; it's a "virtual" priv given to users of chat platforms (Discord, IRC).
